# GroupChat 插件默认配置文件

# 群聊最大数量
max-groups: 10

# 每个群聊最多成员数
max-members-per-group: 100

# 是否开启群聊消息保存
enable-message-history: true

# 群聊消息最大保存条数
max-message-history: 100

# 是否开启默认管理员权限
default-admin-permission: true

# 群聊命令的前缀
command-prefix: "/"

# 是否允许非管理员踢人
allow-kick-by-nonadmin: false

# 每个玩家 @提醒的冷却时间（单位：秒）
notify-cooldown-seconds: 10

# 玩家个性化提醒开关（true 表示允许被提醒）
notify-toggle:
  "uuid字符串": true
  # 示例：
  # "00000000-0000-0000-0000-000000000000": true