name: Message
version: '1.0-SNAPSHOT'
main: com.Message.Message
api-version: '1.21'
author: Bicd
description: 玩家进出服务器提示插件
commands:
  setjoinmsg:
    description: 设置欢迎消息
    usage: /setjoinmsg <消息内容>
    permission: message.admin
  setquitmsg:
    description: 设置离开消息
    usage: /setquitmsg <消息内容>
    permission: message.admin
  setbroadcast:
    description: 设置广播内容
    usage: /setbroadcast <消息内容>
    permission: message.admin
  broadcaststart:
    description: 开始定时广播
    usage: /broadcaststart <秒数>
    permission: message.admin
  x:
    description: 停止定时广播
    usage: /broadcaststop
    permission: message.admin
permissions:
  message.admin:
    description: 管理插件的权限
    default: op
    setdeathmsg:
      description: 设置死亡私聊消息
      usage: /setdeathmsg <消息内容>
      permission: message.admin
      setdeathreset:
        description: 设置玩家重进后是否重置死亡提示
        usage: /setdeathreset <on|off>
        permission: message.admin
        mute:
          description: 禁言玩家
          usage: /mute <玩家名> <时间>
          permission: message.admin
          unmute:
            description: 解除禁言
            usage: /unmute <玩家名>
            permission: message.admin
            fakechat:
              description: 伪装玩家发言
              usage: /fakechat <玩家名> <内容>
              permission: shitplugin.admin
              commands:
                creategroup:
                  description: 创建群聊
                  usage: /creategroup <群名>
                invitegroup:
                  description: 邀请玩家进群
                  usage: /invitegroup <群名> <玩家名>
                joingroup:
                  description: 加入群聊
                  usage: /joingroup <群名>
                leavegroup:
                  description: 退出群聊
                  usage: /leavegroup
                kickgroup:
                  description: 踢出群聊成员
                  usage: /kickgroup <群名> <玩家名>
                grouplist:
                  description: 查看所有群聊
                  usage: /grouplist
                groupmsg:
                  description: 群聊发言
                  usage: /groupmsg <消息>
              setadmin:
                description: 任命管理员
                usage: /setadmin <群名> <玩家名>
                unsetadmin:
                  description: 撤销管理员
                  usage: /unsetadmin <群名> <玩家名>
                  commands:
                    helpmsg:
                      description: 显示群聊插件指令指南
                      usage: /helpmsg
                      message:
                        description: 查看全部指令
                        usage: /message
                        permission: message.admin
