name: GroupChat
version: '1.0'
main: com.groupchat.GroupChat
api-version: '1.21'
author: Bicd
description: 服务器消息插件

commands:
  creategroup:
    description: 创建群聊
    usage: /creategroup <群名>
  invitegroup:
    description: 邀请玩家进群
    usage: /invitegroup <群名> <玩家名>
  joingroup:
    description: 加入群聊
    usage: /joingroup <群名>
  leavegroup:
    description: 退出群聊
    usage: /leavegroup
  switchgroup:
    description: 切换当前活跃群聊
    usage: /switchgroup <群名>
  kickgroup:
    description: 踢出群聊成员
    usage: /kickgroup <群名> <玩家名>
  grouplist:
    description: 查看所有群聊
    usage: /grouplist
  groupmsg:
    description: 群聊发言
    usage: /groupmsg <消息>
  setadmin:
    description: 任命管理员
    usage: /setadmin <群名> <玩家名>
  unsetadmin:
    description: 撤销管理员
    usage: /unsetadmin <群名> <玩家名>
  chathelp:
    description: 显示群聊插件指令指南
    usage: /chathelp
  grouphistory:
    description: 查看当前群聊历史消息（可分页）
    usage: /grouphistory [页码]
  setgrouphistorylimit:
    description: 设置群聊历史消息最大保存条数
    usage: /setgrouphistorylimit <条数>
  groupchat:
    description: 进入群聊聊天模式
    usage: /groupchat
  setannouncement:
    description: 设置群公告
    usage: /setannouncement
  announcement:
    description: 查看当前群聊的公告
    usage: /announcement
  groupmute:
    description: 禁言群成员
    usage: /groupmute
  groupunmute:
    description: 解除群成员禁言
    usage: /groupunmute
  renamegroup:
    description: 修改群名称
    usage: /renamegroup <现群名> <新群名>
  transfergroup:
    description: 转让群聊
    usage: /transfergroup <群名> <新群主玩家名>
  disbandgroup:
    description: 解散群聊
    usage: /disbandgroup <群名>
  groupban:
    description: 将玩家加入群聊黑名单
    usage: /groupban <群名> <玩家名>
  groupunban:
    description: 移除玩家的群聊黑名单
    usage: /groupunban <群名> <玩家名>
